# Generated by Django 5.0.14 on 2025-04-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bone_Tumor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoneCell",
        ),
    ]
